### Upload or update user profile picture
PATCH http://localhost:4000/cloudinary/profile-picture
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjFjMjMyOS1lNThmLTRlMzYtYTcyMy01MTkxZGNmOTcxZmUiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzUyMzg1OTc0LCJleHAiOjE3NTIzODk1NzQsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.CfcffW-0lwCd1dP6zJgx-iIpfXAqjAcHmN1Ujtj6SEk
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="profile.jpg"
Content-Type: image/jpeg

< ../assets/GuarantorPassport.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
