// CREATE A SINGLE NEW USER
POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "Yusuf",
    "lastName": "Falade",
    "email": "faladeyusuf54@gmail.com",
    "password": "Adetomi.544$$"
}

// LOGIN USER
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "faladeyusuf54@gmail.com",
    "password": "Adetomi.544$$"
}

// VERIFY EMAIL
POST http://localhost:4000/api/v1/auth/verify-email
Content-Type: application/json

{
    "token": "jp4kv8l6l6kyckhi23seig",
    "userId": "e5d14e41-ed76-40ad-8f0b-798a94efb708"
}

// RESEND VERIFICATION EMAIL
POST http://localhost:4000/api/v1/auth/resend-verify-email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWQxNGU0MS1lZDc2LTQwYWQtOGYwYi03OThhOTRlZmI3MDgiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NTIyNDgzMjQsImV4cCI6MTc1MjI1MTkyNCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.7WZFCi6ZEC2yl928QpiSVO8erlnwdSi4ZMCj8imK1zo

// REFRESH TOKEN - GET AN ACCESS TOKEN USING THE REFRESH TOKEN
POST http://localhost:4000/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWQxNGU0MS1lZDc2LTQwYWQtOGYwYi03OThhOTRlZmI3MDgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MjI0ODMyNCwiZXhwIjoxNzUyMzM0NzI0LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.ty55UyVfk66f2hZtL5NCkgSVMVpsCZlPb9_LalpxPdo"
}

// LOG OUT
POST http://localhost:4000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWQxNGU0MS1lZDc2LTQwYWQtOGYwYi03OThhOTRlZmI3MDgiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NTIyNDgzMjQsImV4cCI6MTc1MjI1MTkyNCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.7WZFCi6ZEC2yl928QpiSVO8erlnwdSi4ZMCj8imK1zo

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWQxNGU0MS1lZDc2LTQwYWQtOGYwYi03OThhOTRlZmI3MDgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MjI0ODMyNCwiZXhwIjoxNzUyMzM0NzI0LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.ty55UyVfk66f2hZtL5NCkgSVMVpsCZlPb9_LalpxPdo"
}

// LOG OUT ALL DEVICES/SESSIONS
POST http://localhost:4000/api/v1/auth/logout-all-sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWQxNGU0MS1lZDc2LTQwYWQtOGYwYi03OThhOTRlZmI3MDgiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NTIyNDgzMjQsImV4cCI6MTc1MjI1MTkyNCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAwIn0.7WZFCi6ZEC2yl928QpiSVO8erlnwdSi4ZMCj8imK1zo

// FORGOT PASSWORD
POST http://localhost:4000/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com"
}

// RESET PASSWORD
POST http://localhost:4000/api/v1/auth/reset-password
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com",
    "token": "b3ee64ffhbuih97kul284j",
    "password": "Opeyemi.544$$"
}