// CREATE A SINGLE NEW USER
POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "user",
    "email": "testuser@gmail.com",
    "password": "Testuser.544$$"
}

// LOGIN USER
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "Testuser.544$$"
}

// VERIFY EMAIL
POST http://localhost:4000/api/v1/auth/verify-email
Content-Type: application/json

{
    "token": "jp4kv8l6l6kyckhi23seig",
    "userId": "e5d14e41-ed76-40ad-8f0b-798a94efb708"
}

// RESEND VERIFICATION EMAIL
POST http://localhost:4000/api/v1/auth/resend-verify-email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidG9taWxvbGFhYWFhQGdtYWlsLmNvbSIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMjkwNzEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.JXhpJmaC_2m8Fq9BC5ZSZjb_N8E61CH9tJ36SQjxWd8

// REFRESH TOKEN - GET AN ACCESS TOKEN USING THE REFRESH TOKEN
POST http://localhost:4000/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMzczNTEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.ztq6oktfPxn0-d-HsXZOmu0Nht6AfIv1L71zTp6hdq8"
}

// LOG OUT
POST http://localhost:4000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidG9taWxvbGFhYWFhQGdtYWlsLmNvbSIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMjkwNzEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.JXhpJmaC_2m8Fq9BC5ZSZjb_N8E61CH9tJ36SQjxWd8

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMzczNTEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.ztq6oktfPxn0-d-HsXZOmu0Nht6AfIv1L71zTp6hdq8"
}

// LOG OUT ALL DEVICES/SESSIONS
POST http://localhost:4000/api/v1/auth/logout-all-sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidG9taWxvbGFhYWFhQGdtYWlsLmNvbSIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMjkwNzEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.JXhpJmaC_2m8Fq9BC5ZSZjb_N8E61CH9tJ36SQjxWd8

// FORGOT PASSWORD
POST http://localhost:4000/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com"
}

// RESET PASSWORD
POST http://localhost:4000/api/v1/auth/reset-password
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com",
    "token": "b3ee64ffhbuih97kul284j",
    "password": "Opeyemi.544$$"
}

// CHANGE PASSWORD
POST http://localhost:4000/api/v1/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidG9taWxvbGFhYWFhQGdtYWlsLmNvbSIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMjkwNzEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.JXhpJmaC_2m8Fq9BC5ZSZjb_N8E61CH9tJ36SQjxWd8

{
    "currentPassword": "Opeyemi.544$$",
    "newPassword": "Omolomo.544$$"
}