// CREATE A SINGLE NEW USER
POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "Tomilola",
    "lastName": "Akanni",
    "email": "tomilolaaaaa@gmail.com",
    "password": "Adetomi.544$$"
}

// VERIFY EMAIL
POST http://localhost:4000/api/v1/auth/verify-email
Content-Type: application/json

{
    "token": "kf9hbwilwrdi96t6kb7yu",
    "userId": "0b91060d-dc39-42c1-aa74-2305f5f80f41"
}

// RESEND VERIFICATION EMAIL
POST http://localhost:4000/api/v1/auth/resend-verify-email
Authorization: Bearer access-token
