
// GET ALL SUBSCRIBERS
GET http://localhost:4000/api/v1/newsletter/subscribers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzZkZDYyNi1mOWJiLTQ3YzMtOTI3MC03YzgxODdlODJjMDciLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImZhbGFkZXl1c3VmNTRAZ21haWwuY29tIiwiaWF0IjoxNzU0MDQzMjcwLCJleHAiOjE3NTQwNDY4NzAsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.KKSiPTtt7Nh29kyNX-znk4eiu1e5vh8ewxiUe1fUOLc