// SUBSCRIBE A USER TO NEWSLETTER
POST http://localhost:4000/api/v1/newsletter/subscribe 
Content-Type: application/json

{
    "category": "tech",
    "email": "tomilolaaaaa@gmail.com"
}

// UNSUBSCRIBE A USER FROM NEWSLETTER
POST http://localhost:4000/api/v1/newsletter/unsubscribe
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com"
}

// RESUBSCRIBE A USER FROM NEWSLETTER
POST http://localhost:4000/api/v1/newsletter/resubscribe
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com"
}
