// GET SINGLE TRANSACTION BY PAYSTACK PAYMENT REFERENCE
GET http://localhost:4000/transactions/4p10fxz3kw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYzZkZDYyNi1mOWJiLTQ3YzMtOTI3MC03YzgxODdlODJjMDciLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImZhbGFkZXl1c3VmNTRAZ21haWwuY29tIiwiaWF0IjoxNzU0MzEwODIxLCJleHAiOjE3NTQzMTQ0MjEsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.ridwwm8NR4aj14Jx-3fB7xsqnD-WWYNiawdKKIoZkw8