// DELETE ANY SINGLE USER (ADMIN)
DELETE http://localhost:4000/api/v1/users/32e09f9f-95da-471d-930c-32c12a7f8aaa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjA3ZWExNC0zMDFkLTRmZDYtOWFjOS1kNzViYmY4YTYyYTQiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzUyMzI2Nzg2LCJleHAiOjE3NTIzMzAzODYsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.OJF0JdvbQNVU0xu_kiLlPRccgNbl3e7dh4megRXbec8

// DELETE OWN ACCOUNT (SIGNED IN USER)
DELETE http://localhost:4000/api/v1/users/me/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjA3ZWExNC0zMDFkLTRmZDYtOWFjOS1kNzViYmY4YTYyYTQiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzUyMzI2Nzg2LCJleHAiOjE3NTIzMzAzODYsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.OJF0JdvbQNVU0xu_kiLlPRccgNbl3e7dh4megRXbec8