// GET USER OWN PROFILE - USER
GET http://localhost:4000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjA3ZWExNC0zMDFkLTRmZDYtOWFjOS1kNzViYmY4YTYyYTQiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzUyMzI2Nzg2LCJleHAiOjE3NTIzMzAzODYsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.OJF0JdvbQNVU0xu_kiLlPRccgNbl3e7dh4megRXbec8

// GET ALL USERS - ADMIN
GET http://localhost:4000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjA3ZWExNC0zMDFkLTRmZDYtOWFjOS1kNzViYmY4YTYyYTQiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzUyMzI2Nzg2LCJleHAiOjE3NTIzMzAzODYsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.OJF0JdvbQNVU0xu_kiLlPRccgNbl3e7dh4megRXbec8

// GET SINGLE USER - ADMIN
GET http://localhost:4000/api/v1/users/e5d14e41-ed76-40ad-8f0b-798a94efb708
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjA3ZWExNC0zMDFkLTRmZDYtOWFjOS1kNzViYmY4YTYyYTQiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaWF0IjoxNzUyMzI2Nzg2LCJleHAiOjE3NTIzMzAzODYsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCJ9.OJF0JdvbQNVU0xu_kiLlPRccgNbl3e7dh4megRXbec8