// GET USER PROFILE
GET http://localhost:4000/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidG9taWxvbGFhYWFhQGdtYWlsLmNvbSIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMjkwNzEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.JXhpJmaC_2m8Fq9BC5ZSZjb_N8E61CH9tJ36SQjxWd8

// UPDATE USER PROFILE
PATCH http://localhost:4000/api/v1/users/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidG9taWxvbGFhYWFhQGdtYWlsLmNvbSIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMjkwNzEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.JXhpJmaC_2m8Fq9BC5ZSZjb_N8E61CH9tJ36SQjxWd8

{
    "userName": "tom tom"
}

// GET ALL USERS
GET http://localhost:4000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjkxMDYwZC1kYzM5LTQyYzEtYWE3NC0yMzA1ZjVmODBmNDEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidG9taWxvbGFhYWFhQGdtYWlsLmNvbSIsImlhdCI6MTc1MjI4NzExMiwiZXhwIjoxNzUyMjkwNzEyLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAifQ.JXhpJmaC_2m8Fq9BC5ZSZjb_N8E61CH9tJ36SQjxWd8

